### ISSUE TITLE
Compatibility Certification Request for Eclipse Krazo 2.0.1

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/mvc-api#66]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://eclipse.org)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Krazo 2.0.1](https://eclipse-ee4j.github.io/krazo/downloads/2.0.1.html)
- [x] Specification Name, Version and download URL:
   [Jakarta MVC 2.0](https://jakarta.ee/specifications/mvc/2.0)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta MVC TCK 2.0.0](https://download.eclipse.org/jakartaee/mvc/2.0/jakarta-mvc-tck-2.0.0.zip)
  SHA-256: `27a09b18169e46571898375d2eb1d05000301828c5d16dfc5d56e882690d55ed`
- [x] Public URL of TCK Results Summary:
  https://eclipse-ee4j.github.io/krazo/certifications/jakarta-mvc/2.0.1/TCK-Results.html
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  OpenJDK Runtime Environment (build 1.8.0_292-b10)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  - Linux 5.11.18-200.fc33.x86_64 GNU/Linux
  - OpenJDK Runtime Environment (build 1.8.0_292-b10)
  - Testrun 1: Eclipse GlassFish 6.0.0
  - Testrun 2: WildFly 23.0.2.Final
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by chkal** [comment]
Ah, ok. I wasn't aware that this is required. I'll fix this.

**Comment by chkal** [comment]
@ivargrimstad I just updated the issue. I hope everything is fine now?

**Comment by ivargrimstad** [comment]
Yes, perfect!
Only a minor cosmetic thing. Since we run 2 TCK results, the anchor-links in the embedded HTML need to be edited for the second result section. 

For example, if you click on "Testrun 2 (WildFly 23.0.2.Final)", then on either of the links "Summary", "Package List" or "Test Results", then you will be brought up to the GlassFish section. 

The fix is kind of tedious, but easy. In the 2.0 results, I added "2" to the anchors and corresponding links for the Testresult 2 section.

But not a big deal, just cosmetic ;)

**Comment by chkal** [comment]
Good catch. I'll check that. I was already thinking about using `<iframe>` to include the results. Simpler, but dirty. ;-)

**Comment by chkal** [comment]
Fixed! Some regex-based search & replace did the trick. :laughing:
